apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: postgres
